# Generated by Django 4.2.6 on 2023-10-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('preco', models.FloatField()),
                ('quantidade_estoque', models.IntegerField()),
                ('categoria', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
    ]
